#+title: gptel-magit: LLM functionality for magit

[[https://stable.melpa.org/#/gptel-magit][file:https://melpa.org/packages/gptel-magit-badge.svg]]

Uses the fantastic [[https://github.com/karthink/gptel][gptel]] to
extend the equally fantastic [[https://magit.vc/][magit]] with some
LLM-powered functionality.

Functionality is provided for:

- Generating commit messages
- Providing optional rationale to guide generated commit messages
- Explaining diffs

* Installation

Install the package and run =gptel-magit-install= at an appropriate
time, for example:

#+begin_src elisp
  (use-package gptel-magit
    :ensure t
    :hook (magit-mode . gptel-magit-install))
#+end_src

* Usage

** Commit messages

You can generate a commit message in two ways:

1. In the magit transient commit buffer, you can press =g= to create a
   commit with a pre-generated message.
2. In an already started git-commit buffer, you can press =M-g= to
   generate a message.

To provide extra context about why the change was made, generate with a
rationale instead:

1. In the magit transient commit buffer, press =r= to enter a rationale
   before creating the commit.
2. In an already started git-commit buffer, press =M-r= to enter a
   rationale before generating the message.

Submit the rationale buffer with =C-c C-c=, or cancel it with =C-c C-k=.
Leaving the buffer empty generates the commit message without additional
rationale.

** Diff explanation

With the cursor placed on a magit diff section, you can request an
explanation by pressing =d= (to invoke the diff action), and then =x=.


* Customisation

Prompts, and some other options can be customised, see
`customize-group magit-gptel`.
